version: '3.1'

services:
  mariadb:
    image: mariadb:10.11.6
    restart: always
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: room
    ports:
      - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql
